### ISSUE TITLE
Milestone 1 - TA commets

### ISSUE THREAD

**Issue by anodaini** [UBC-MDS/sktidy#39]
> FWD feedback on submission: - Summary and functions could be clearer, an example would be better than referencing an existing package - In function docs, if multiple functions act on the same object, the description of the object should be consistent (here "X") - It's not clear why the features are needed in addition to the model, why not just the model? why not the model, X and y?

- [x] Summary and functions could be clearer, an example would be better than referencing an existing package #37
- [x] In function docs, if multiple functions act on the same object, the description of the object should be consistent (here "X") #42 
- [ ] It's not clear why the features are needed in addition to the model, why not just the model? why not the model, X and y? (Addressed below)

**Comment by heidi-ye** [comment]
- revised variable names for more consistency

**Comment by anodaini** [comment]
Hello Peter Gysbers, regarding your comments about why we are passing the features along with the model. 
For `tidy_lr` and `augment_lr`, we are calculating the residuals so we the function needs to have access to the X and y part of the data. As for the `tidy_kmeans` and `augment_kmeans`, as you know, kmeans is an unsupervised learning model and therefore there is no y really. We are passing X which is the dataframe containing the data that the user wants append a labels column to.

**Comment by pgysbers** [comment]
Yes I agree. I think the question referred to the `tidy` functions, the only reason you need the dataframe is to get the feature names, correct? (that is they are not stored by the model?)

**Comment by anodaini** [comment]
That is correct!
